/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "remotedb.h"

bool_t
xdr_remotedb_in (XDR *xdrs, remotedb_in *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->arg1, 128))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_remotedb_out (XDR *xdrs, remotedb_out *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->res1, 128))
		 return FALSE;
	return TRUE;
}
