/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "remotedb.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
remotedb_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		remotedb_in remotedbproc_1_arg;
		remotedb_in add_to_database_1_arg;
		remotedb_in remove_from_database_1_arg;
		remotedb_in lookup_name_1_arg;
		remotedb_in list_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case REMOTEDBPROC:
		_xdr_argument = (xdrproc_t) xdr_remotedb_in;
		_xdr_result = (xdrproc_t) xdr_remotedb_out;
		local = (char *(*)(char *, struct svc_req *)) remotedbproc_1_svc;
		break;

	case ADD_TO_DATABASE:
		_xdr_argument = (xdrproc_t) xdr_remotedb_in;
		_xdr_result = (xdrproc_t) xdr_remotedb_out;
		local = (char *(*)(char *, struct svc_req *)) add_to_database_1_svc;
		break;

	case REMOVE_FROM_DATABASE:
		_xdr_argument = (xdrproc_t) xdr_remotedb_in;
		_xdr_result = (xdrproc_t) xdr_remotedb_out;
		local = (char *(*)(char *, struct svc_req *)) remove_from_database_1_svc;
		break;

	case LOOKUP_NAME:
		_xdr_argument = (xdrproc_t) xdr_remotedb_in;
		_xdr_result = (xdrproc_t) xdr_remotedb_out;
		local = (char *(*)(char *, struct svc_req *)) lookup_name_1_svc;
		break;

	case LIST:
		_xdr_argument = (xdrproc_t) xdr_remotedb_in;
		_xdr_result = (xdrproc_t) xdr_remotedb_out;
		local = (char *(*)(char *, struct svc_req *)) list_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (REMOTEDB_PROG, REMOTEDB_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, REMOTEDB_PROG, REMOTEDB_VERS, remotedb_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (REMOTEDB_PROG, REMOTEDB_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, REMOTEDB_PROG, REMOTEDB_VERS, remotedb_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (REMOTEDB_PROG, REMOTEDB_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
